//Videos data

export const videoData = [
    {
        video: require('../../storage/videos/video1.mp4'),
        title: 'Event1',
        description: 'Crowdfunding event 1 description',
        donations: '359',
        isDonate: false,
    },
    {
        video: require('../../storage/videos/video2.mp4'),
        title: 'Event2',
        description: 'Crowdfunding event 2 description',
        donations: '250',
        isDonate: false,
    },
    {
        video: require('../../storage/videos/video3.mp4'),
        title: 'Event3',
        description: 'Crowdfunding event 3 description',
        donations: '9',
        isDonate: false,
    },
    {
        video: require('../../storage/videos/video4.mp4'),
        title: 'Event4',
        description: 'Crowdfunding event 4 description',
        donations: '4699',
        isDonate: false,
    },
]

//Friends Profile data

export const FriendsProfileData = [
    {
        name: 'Biva',
        accountName: 'Weeeeeeee',
        profileImage: require('../../storage/images/Biva.jpg'),
        posts: 69,
        followers: 678,
        follow: false,
    },
    {
        name: 'Biva',
        accountName: 'Weeeeeeee',
        profileImage: require('../../storage/images/Biva.jpg'),
        posts: 69,
        followers: 678,
        follow: false,
    },
    {
        name: 'Biva',
        accountName: 'Weeeeeeee',
        profileImage: require('../../storage/images/Biva.jpg'),
        posts: 69,
        followers: 678,
        follow: false,
    },
    {
        name: 'Biva',
        accountName: 'Weeeeeeee',
        profileImage: require('../../storage/images/Biva.jpg'),
        posts: 69,
        followers: 678,
        follow: false,
    },
    {
        name: 'Biva',
        accountName: 'Weeeeeeee',
        profileImage: require('../../storage/images/Biva.jpg'),
        posts: 69,
        followers: 678,
        follow: false,
    },
    {
        name: 'Biva',
        accountName: 'Weeeeeeee',
        profileImage: require('../../storage/images/Biva.jpg'),
        posts: 69,
        followers: 678,
        follow: false,
    },
    {
        name: 'Biva',
        accountName: 'Weeeeeeee',
        profileImage: require('../../storage/images/Biva.jpg'),
        posts: 69,
        followers: 678,
        follow: false,
    },
    {
        name: 'Biva',
        accountName: 'Weeeeeeee',
        profileImage: require('../../storage/images/Biva.jpg'),
        posts: 69,
        followers: 678,
        follow: false,
    },
    {
        name: 'Biva',
        accountName: 'Weeeeeeee',
        profileImage: require('../../storage/images/Biva.jpg'),
        posts: 69,
        followers: 678,
        follow: false,
    },
    {
        name: 'Biva',
        accountName: 'Weeeeeeee',
        profileImage: require('../../storage/images/Biva.jpg'),
        posts: 69,
        followers: 678,
        follow: false,
    },
    {
        name: 'Biva',
        accountName: 'Weeeeeeee',
        profileImage: require('../../storage/images/Biva.jpg'),
        posts: 69,
        followers: 678,
        follow: false,
    },
    {
        name: 'Biva',
        accountName: 'Weeeeeeee',
        profileImage: require('../../storage/images/Biva.jpg'),
        posts: 69,
        followers: 678,
        follow: false,
    },
    {
        name: 'Biva',
        accountName: 'Weeeeeeee',
        profileImage: require('../../storage/images/Biva.jpg'),
        posts: 69,
        followers: 678,
        follow: false,
    },
    {
        name: 'Biva',
        accountName: 'Weeeeeeee',
        profileImage: require('../../storage/images/Biva.jpg'),
        posts: 69,
        followers: 678,
        follow: false,
    },
    {
        name: 'Biva',
        accountName: 'Weeeeeeee',
        profileImage: require('../../storage/images/Biva.jpg'),
        posts: 69,
        followers: 678,
        follow: false,
    }
] 